
name: Build an appImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        # You may pin to the exact commit or the version.
        # uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d
        uses: cachix/install-nix-action@v14.1
        with:

          # Set NIX_PATH environment variable.
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build nix
        run: nix-build "<nixpkgs>" -A pkgsStatic.nix
      - name: copy results
        run: |
          nix-build nix/appimage.nix
 
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: nixStatic
          path: ./result/*.AppImage
